# Pytorch Functions

In this notebook, I'll explain below functions in pytorch
- torch.zeroes() : Creates a tensor with all zero values
- torch.

In [2]:
# Import modules
import torch

## 1. torch.zeroes()

This function is used to create a tensor with zero value. Its very handy whenever we wanted to have a tensor initialized with zero values.

In [4]:
# Example 1 - All values are zero
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In above example, we have created a tensor with four rows and five columns. As expected, all the values are zero.

In [5]:
# Example 2 - Negative dimension doesn't work
torch.zeros(-1)

RuntimeError: Trying to create tensor with negative dimension -1: [-1]

## 2. torch.numpy()

This function is used to create numpy array. 

In [8]:
# Example 1: Converting a torch tensor to a numpy array
t = torch.tensor([[1,2,3], [4,5,6]])
print(t)
t.numpy()

tensor([[1, 2, 3],
        [4, 5, 6]])


array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

## 3. torch.cat()

This function concatenates multiple tensors along a specified dimension. The constraint is to have tensors of same shape, except in the concatenating dimension). Its widely used in ResNet DNN for adding previous layers to forward layers.
It'd different from addition in the way that there is no element wise addition

In [14]:
# Example 1: Concatenating two tensors
t1 = torch.tensor([[1,2,3], [4,5,6]])
t2 = torch.tensor([[3,2,1], [6,5,4]])

In [15]:
# Concatenating across dimension 0
result = torch.cat([t1, t2], dim=0) 
display(result)

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 2, 1],
        [6, 5, 4]])

In [17]:
# Concatenating across dimension 1
result = torch.cat([t1, t2], dim=1) 
display(result)

tensor([[1, 2, 3, 3, 2, 1],
        [4, 5, 6, 6, 5, 4]])

As seen from above output, we could see output tensor of different dimension based on dimension provided

In [19]:
# Error: Concatenating two tensors of different shapes result in an erro
t1 = torch.tensor([[1,2,3], [4,5,6]])
t2 = torch.tensor([[7,8]])
result = torch.cat([t1,t2], dim=0)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 2 in dimension 1 at ..\aten\src\TH/generic/THTensor.cpp:711

We can see concatenating two tensors with different shape is not allowed and throws and error of size mismatch

## 4. torch.flatten()

This function flattens a tensor along a specified dimension. If dimension is not specified, zero is taken by default. Its mainly used in in the final layer of a DNN

In [24]:
# Example 1: Flattening a tensor along dimension 0
t = torch.tensor([[[1,2], [3,4]], [[5,6], [7,8]]])
print("*** Before flattening ***")
print(t)
print("*** After flattening ***")
torch.flatten(t)

*** Before flattening ***
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
*** After flattening ***


tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
# Example 2: Flattening a tensor along dimension 1
torch.flatten(t, start_dim=1)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

## 5. torch.save()

This function saves a specified tensor to a disk. This allows re-use of tensors which we might have got through heavy computations and save our work for later use. torch.load() is used to load the saved tensor

In [26]:
# Example: Save a tensor to disk
t = torch.tensor([[1,2,3], [4,5,6]])
torch.save(t, 'tensor.pt')

The above code saves a tensor 't' to a disk at current working directory with name 'tensor.pt'

In [27]:
# Load saved tensor 'tensor.pt'
t = torch.load('tensor.pt')
print(t)

tensor([[1, 2, 3],
        [4, 5, 6]])


We could see from above code, our saved tensor has been loaded back.
This function is very useful in cases of DNN which involve heavy computation on tensors and saving them to the disk. Highly used in image classification tasks. It avoids issues such as CUDA out of memory.

# Conclusion

In this notebook we looked at some functions available in pytorch for performing operations on a tensor. I tried to cover variety of functions in order to cover different type of functions available. 

# References
- [PyTorch official documentation](https://pytorch.org/docs/stable/tensors.html)